// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice_API.Classes;

namespace Practice_API.Migrations
{
    [DbContext(typeof(AnimalContext))]
    partial class AnimalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Practice_API.Classes.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsMale")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            IsMale = true,
                            Name = "Tom",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            IsMale = true,
                            Name = "Jerry",
                            Type = "Mouse"
                        },
                        new
                        {
                            AnimalId = 3,
                            IsMale = false,
                            Name = "MiMi",
                            Type = "Cat"
                        });
                });

            modelBuilder.Entity("Practice_API.Classes.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .HasColumnType("text");

                    b.Property<int>("NumberofCans")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            FoodName = "Meat",
                            NumberofCans = 50
                        },
                        new
                        {
                            FoodId = 2,
                            FoodName = "Fish",
                            NumberofCans = 40
                        });
                });

            modelBuilder.Entity("Practice_API.Classes.FoodDistribution", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnough")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("AnimalId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodDistributions");

                    b.HasData(
                        new
                        {
                            AnimalId = 3,
                            FoodId = 2,
                            IsEnough = true,
                            Quantity = 30
                        },
                        new
                        {
                            AnimalId = 1,
                            FoodId = 1,
                            IsEnough = false,
                            Quantity = 60
                        });
                });

            modelBuilder.Entity("Practice_API.Classes.FoodDistribution", b =>
                {
                    b.HasOne("Practice_API.Classes.Animal", "Animal")
                        .WithMany("FoodDistributions")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice_API.Classes.Food", "Food")
                        .WithMany("FoodDistributions")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Practice_API.Classes.Animal", b =>
                {
                    b.Navigation("FoodDistributions");
                });

            modelBuilder.Entity("Practice_API.Classes.Food", b =>
                {
                    b.Navigation("FoodDistributions");
                });
#pragma warning restore 612, 618
        }
    }
}
