version: '3.8'

services:
    dbAnimal:
        image: mysql:8.0.27

        volumes:
            - mysql-data-animal:/var/lib/mysql

        environment:
            MYSQL_ROOT_PASSWORD: "khoa333"
            MYSQL_DATABASE: "Animal"

        ports:
            - "3210:3306"

volumes:
    mysql-data-animal: 