version: '3.8'

services:
    dbBlog:
        image: mysql:8.0.27

        volumes:
            - mysql-data-blog:/var/lib/mysql

        environment:
            MYSQL_ROOT_PASSWORD: "khoa345"
            MYSQL_DATABASE: "Blog"

        ports:
            - "3468:3306"

volumes:
    mysql-data-blog: 