// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_API.Classes;

namespace Test_API.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20211216093446_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Test_API.Classes.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 11,
                            IsDeleted = true,
                            Rating = 4,
                            Url = "test.com"
                        },
                        new
                        {
                            BlogId = 12,
                            IsDeleted = false,
                            Rating = 5,
                            Url = "dev.com"
                        },
                        new
                        {
                            BlogId = 13,
                            IsDeleted = false,
                            Rating = 3,
                            Url = "learnAPI.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
